### ISSUE TITLE
CPU Usage always 1%

### ISSUE THREAD

**Issue by mlapaglia** [afaqurk/linux-dash#331] opened 2015-10-02 17:45 UTC
First off, awesome app, nice and easy to use!

When I'm looking at the CPU usage, it's always either 0 or 1%. When running the cpu_utilization.sh script manually and uncommenting the echo command in the script, it also is only 0 or 1. I put the server under 100% load but still only 0 or 1%.

Running latest Debian with 3.16.0-4-amd64 kernel.

I have the latest code from master.

I've got a quad core 8 thread CPU. Here is what the CPU info section says.

Architecture	x86_64
BogoMIPS	6784.85
Byte Order	Little Endian
CPU MHz	1891.117
CPU family	6
CPU max MHz	3800.0000
CPU min MHz	1600.0000
CPU op-mode(s)	32-bit, 64-bit
CPU(s)	8
Core(s) per socket	4
L1d cache	32K
L1i cache	32K
L2 cache	256K
L3 cache	8192K
Model	58
Model name	Intel(R) Xeon(R) CPU E3-1245 V2 @ 3.40GHz
NUMA node(s)	1
NUMA node0 CPU(s)	0-7
On-line CPU(s) list	0-7
Socket(s)	1
Stepping	9
Thread(s) per core	2
Vendor ID	GenuineIntel
Virtualization	VT-x

**Comment by afaqurk** [comment] 2015-10-02 18:56
Thank you for the debug info. I have marked this as a bug.

For what its worth, the demo shows that the CPU utilization changes over time. So this might be isolated to a specific environment (Debian, quad core, etc.).

I will take a look into this during the weekend. Feel free to inspect / share if you know what it could be.

**Comment by afaqurk** [comment] 2015-10-04 15:12
@mlapaglia I was not able to reproduce your issue. I've tried several VMs, including the [demo](http://linuxdash.afaqtariq.com). They all report higher relatively close percentages (definitely higher than 1%), especially when system load increases. It doesn't seem like a bug in the `cpu_utilization.sh` script.

Are you able to run `top` and confirm that the reported cpu idle number is higher than 1%?

**Comment by mlapaglia** [comment] 2015-10-05 14:10
top is showing higher than 1% usage. Here is what I'm seeing today:

![image](https://cloud.githubusercontent.com/assets/4184746/10282500/45debf62-6b49-11e5-8bef-041edbc99cf9.png)

The first CPU says 2% while the two numbers after are higher.

**Comment by nicolasdanelon** [comment] 2015-10-06 13:26
I don't wanna be a troll.. neither create a new issue for this question.. so spammer here
q:
All right JavaScript, HTML and CSS are for showing data in browser but..
Angular, Python, Shell, Go and PHP? all together? why? what about ruby and pearl? you miss them dude!

**Comment by afaqurk** [comment] 2015-10-10 03:03
@mlapaglia That is not how that module should be showing the data at all.

Seems like a bug in how `cpu_utilization.sh` is parsing the CPU data specifically for your machine. Must have something to do with multiple CPU % lines. 

I've marked this as a bug. I will explore an alternative way to display the same data for servers that print CPU data the way your machine does.

**Comment by afaqurk** [comment] 2015-11-08 04:02
@mlapaglia : can you please paste the exact output of ```{your-linux-dash-server}/server/?module=cpu_utilization`` endpoint from a browser?

I would like to use the output to test different parsing techniques to address this issue.

**Comment by mlapaglia** [comment] 2015-11-08 04:17
When I refresh I randomly get "1" and "2" out.

**Comment by mlapaglia** [comment] 2015-11-08 04:22
After upgrading to the latest version I am now seeing proper CPU 
![image](https://cloud.githubusercontent.com/assets/4184746/11018761/691d09c6-85a6-11e5-9ef3-fadc3399c143.png)

Thanks!

**Comment by afaqurk** [comment] 2015-11-08 04:35
Awesome! Glad to see the issue was resolved. 

If you notice anything odd with the CPU utilization module graph, please reopen this issue.

**Closed by afaqurk** 2015-11-08 04:35 UTC
Labels: bug
