### ISSUE TITLE
Centos 6.5 x64 node.js - SyntaxError when clicking network tab

### ISSUE THREAD

**Issue by whukes** [afaqurk/linux-dash#288] opened 2015-02-16 02:21 UTC
Centos 2.6.32-504.8.1.el6.x86_64
node.js 12.0

Linux Dash Server Started!
undefined:0

SyntaxError: Unexpected end of input
    at Object.parse (native)
    at ChildProcess.<anonymous> (/root/linux-dash/server/index.js:35:33)
    at ChildProcess.emit (events.js:110:17)
    at maybeClose (child_process.js:1008:16)
    at Socket.<anonymous> (child_process.js:1176:11)
    at Socket.emit (events.js:107:17)
    at Pipe.close (net.js:476:12)

Not sure what else to attach to help fix.

**Comment by afaqurk** [comment] 2015-02-18 02:04
I'm unable to replicate the issue. 

Can you try adding  ` console.log(req.query.module); ` to line 19 of `index.js`? Then, reload the network tab and check the std out again and post here. 

This will allow us to see exactly which module caused the error. We can debug further from there.

**Comment by whukes** [comment] 2015-02-18 02:09
Here is the new output:

Linux Dash Server Started!
current_ram
ram_intensive_processes
cpu_intensive_processes
swap
disk_partitions
load_avg
load_avg
current_ram
ip_addresses
network_connections
arp_cache
ping
bandwidth
undefined:0


SyntaxError: Unexpected end of input
    at Object.parse (native)
    at ChildProcess.<anonymous> (/root/linux-dash/server/index.js:36:33)
    at ChildProcess.emit (events.js:110:17)
    at maybeClose (child_process.js:1008:16)
    at Socket.<anonymous> (child_process.js:1176:11)
    at Socket.emit (events.js:107:17)
    at Pipe.close (net.js:476:12)

**Comment by afaqurk** [comment] 2015-02-18 13:13
Awesome. Now we know that the bandwidth module is the culprit. But that script is running fine for me. 

Can you run the following in terminal from inside the linux dash folder: `./server/modules/shell_files/bandwidth.sh` and post your results?

Hopefully, this will be the last part of the debugging process. From the results of that script, we should be able to tell what the output of the bandwidth module is and why it is throwing an error when Node processes it.

**Comment by whukes** [comment] 2015-02-18 16:26
I see similar JSON output to what you posted in your edit:

# ./server/modules/shell_files/bandwidth.sh 
[
{ "interface": "lo:", "tx": 2044728955, "rx": 2044728955 },
{ "interface": "eth0:", "tx": 311325549092, "rx": 36492271193 }
]

Additionally, I tried it via http://<ip address>/server/?module=bandwidth and got similar output:
[{"interface":"lo:","tx":2044744801,"rx":2044744801},{"interface":"eth0:","tx":311325589481,"rx":36492285297}]

Weird.

**Comment by afaqurk** [comment] 2015-02-18 17:46
Weird indeed. But thankfully, it seems like an issue with weird characters across systems rather than a bug in logic (presumably).

Here's something I would like to rule out before I try to debug this further:

Try running this in terminal from the linux dash directory: `./server/modules/python_files/speedtest_cli.py`

And also, see if the web version of it works for you too:  http://your-server/server/?module=internet_speed

**Note**: it will take a while to give you a result (20-50 seconds) since it is running a speedtest.net test.

This will allow me rule out that it isn't the next module in the series which is causing the error, allowing me to focus on the bandwidth.sh script.

Thanks for your patience with this.

**Comment by whukes** [comment] 2015-02-18 17:51
Results from ./server/modules/python_files/speedtest_cli.py

Retrieving speedtest.net configuration...
Retrieving speedtest.net server list...
Testing from Comcast Business Communications (50.X.X.X)...
Selecting best server based on latency...
Hosted by Tulix Systems, Inc (Atlanta, GA) [17.79 km]: 18.132 ms
Testing download speed........................................
Download: 86.23 Mbits/s
Testing upload speed..................................................
Upload: 17.14 Mbits/s

JSON output: {"Download:":"85.80 Mbits/s","Upload:":"17.21 Mbits/s"}

Thank you for taking the time to help me troubleshoot.  Anything I can do, let me know.

**Comment by afaqurk** [comment] 2015-02-18 18:04
Awesome. I think I have enough to go on. It is definitely a weird system character issue. The JSON responses you are getting are perfectly fine. 

I will investigate this further tonight. Marking this as a bug.

**Comment by afaqurk** [comment] 2015-02-18 23:51
Could you try changing this:

```js
command.on('close', function(code) {
	if (code === 0) res.send(JSON.parse(output));
	else res.sendStatus(500);
});
```

to this:

```js
command.on('close', function(code) {
	console.log(code);
	console.log(output.toString());
	if (code === 0) res.send(JSON.parse(output));
	else res.sendStatus(500);
});
```

and then reload the network tab and add the output before the syntax error here.

**Comment by whukes** [comment] 2015-02-19 01:00
Started the server with 'node server' then http://server/#/network.  

Linux Dash Server Started!
ip_addresses
network_connections
arp_cache
ping
bandwidth
0
[
{ "interface": "lo:", "tx": 2145279403, "rx": 2145279403 },
{ "interface": "eth0:", "tx": 336053048399, "rx": 41654339114 }
]

0

undefined:0

**Comment by afaqurk** [comment] 2015-02-20 00:00
So, I was able to reproduce your issue. I believe I have a solution for your issue. 

Change [index.js on line 35](https://github.com/afaqurk/linux-dash/blob/master/server/index.js#L35), from this:

```js
if (code === 0) res.send(JSON.parse(output));
```

to this:

```js
if (code === 0) res.send(output.toString());
```
Depending on if it works for you, I will update the project to account for this issue on Cent OS 6.5 with a more permanent fix.

**Comment by whukes** [comment] 2015-02-20 04:07
That resolved the syntax error.  Thanks for your help.  Great project.

**Closed** 2015-02-20 11:51 UTC
Labels: bug
